/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const PROPOSE_INSTRUCTIONS = `创建一个新的 OvseSpec 变更，并一次性生成进入实现前所需的计划产物。

保留原命令意图：用户描述想做什么，你负责创建 change，并生成 proposal.md、design.md、tasks.md 等 schema 要求的产物。团队版增强只是在原流程上补充协作信息，不改变“提案”的核心职责。

我会创建这些产物：
- proposal.md：做什么、为什么做
- design.md：怎么做、关键取舍
- tasks.md：实现步骤

准备实现时，运行 /ovsx:apply

---

**输入**：\`/ovsx:propose\` 后面的参数可以是 kebab-case 变更名，也可以是用户想构建或修复的自然语言描述。

**团队协作增强**

- 如果变更涉及多个仓库、模块、服务、接口契约、团队或发布窗口，必须在产物里记录影响范围、协作方、评审/验收路径、迁移或回滚风险。
- 团队字段采用最小必填集：影响 repo/module/service、owner、reviewer、acceptance、rollback、handoff。能确认就填写，不能确认就标为 unknown/TBD 并说明需要谁确认；不要直接省略。
- 如果用户提到 workspace、多仓、多团队，优先用 \`ovsespec workspace list --json\` 和 \`ovsespec workspace doctor --json\` 获取可用上下文；如果上下文不可用或不明确，向用户询问仓库/模块映射，不要猜。
- 如果变更涉及 Controller、API route、DTO、request/response schema、错误包装、advmock 或接口契约，必须在 proposal/design/tasks 中保留结构化 API/YAPI 清单，而不是只在对话里说明。
- API/YAPI 清单至少包含：\`method + path\`、\`program_name\`、\`service_id\`、\`interface_id\`、分类、owner/reviewer、Controller/handler、DTO、request/response、错误包装、Mock/advmock 场景、同步状态或阻塞项。
- 如果新接口还没有 \`interface_id\`，明确写 \`interface_id: new/unknown\`，并在 tasks.md 加入“创建 YAPI 接口、写入 Mock/advmock、回读 audit”的 checkbox。
- 不要把机器本地绝对路径写入长期产物，除非用户明确要求。优先使用仓库名、workspace link 名、包名、模块名、服务名。
- 单仓或个人小改动保持轻量，只在有实际协作价值时补充团队字段。

**步骤**

1. **确认目标**

   如果没有明确输入，使用 **AskUserQuestion tool**（开放问题，不提供预设选项）询问：
   > “你想做哪个变更？请描述要构建、修复或调整的内容。”

   从用户描述中推导 kebab-case 变更名，例如 “add user authentication” -> \`add-user-auth\`。

   **重要**：在理解用户目标前不要继续。

2. **创建变更目录**

   \`\`\`bash
   ovsespec new change "<name>"
   \`\`\`

   这会在 \`ovsespec/changes/<name>/\` 下创建带 \`.ovsespec.yaml\` 的变更骨架。

3. **获取产物顺序**

   \`\`\`bash
   ovsespec status --change "<name>" --json
   \`\`\`

   解析 JSON，读取：
   - \`applyRequires\`：实现前必须完成的产物 ID，例如 \`["tasks"]\`
   - \`artifacts\`：所有产物的状态和依赖关系

4. **按依赖顺序生成产物，直到实现就绪**

   使用 **TodoWrite tool** 跟踪产物生成进度。

   按依赖顺序循环处理所有 ready 状态的产物：

   a. 对每个 \`ready\` 产物：
      - 获取说明：
        \`\`\`bash
        ovsespec instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - instructions JSON 包含：
        - \`context\`：项目背景，作为约束使用，不要复制到输出文件
        - \`rules\`：产物规则，作为约束使用，不要复制到输出文件
        - \`template\`：输出文件结构
        - \`instruction\`：当前 schema 对该产物的具体指导
        - \`outputPath\`：要写入的路径
        - \`dependencies\`：需要读取的已完成依赖产物
      - 读取所有已完成依赖产物作为上下文。
      - 按 \`template\` 结构创建产物文件。
      - 遵守 \`context\` 和 \`rules\`，但不要把这些块原样写进文件。
      - 如果团队信息相关，在合适章节补充：影响 repo/module/service、owner/reviewer、acceptance、协作顺序、契约兼容、发布/迁移/rollback、handoff。
      - 如果 API/YAPI 相关，在产物里保留同一组结构化字段；proposal.md 放影响和目标接口，design.md 放契约、同步和 Mock/advmock 方案，tasks.md 放实现、测试、YAPI create/update、Mock/advmock、audit 的 checkbox。
      - PaaS test deploy 不自动并入 apply；如果需要部署验证，在 tasks.md 中写清楚触发 \`/ovsx:paas-test-deploy\` 的前置条件和验证口径。
      - 简短汇报：\`Created <artifact-id>\`。

   b. 每创建一个产物后，重新运行：
      \`\`\`bash
      ovsespec status --change "<name>" --json
      \`\`\`
      当 \`applyRequires\` 中的全部产物都为 \`done\` 时停止。

   c. 如果产物需要用户输入或团队边界不清楚，使用 **AskUserQuestion tool** 澄清，然后继续。

5. **展示最终状态**

   \`\`\`bash
   ovsespec status --change "<name>"
   \`\`\`

**输出**

完成后用中文总结：
- 变更名和位置
- 已创建的产物及简要说明
- 如适用，列出团队协作摘要：影响仓库/模块、owner/reviewer、交接点、发布或契约风险
- 如适用，列出 API/YAPI 摘要：\`method + path\`、\`service_id/interface_id\`、Mock/advmock 场景、sync/audit 阻塞项
- 当前状态：“所有实现前产物已完成，可以开始实现。”
- 提示：“运行 \`/ovsx:apply\` 或直接让我实现，开始处理任务。”

**产物生成准则**

- 遵循 \`ovsespec instructions\` 返回的 \`instruction\` 字段。
- schema 定义产物应该包含什么，就按 schema 写。
- 生成新产物前必须读取依赖产物。
- 使用 \`template\` 作为文件结构，并填充实际内容。
- 保留原有 proposal/design/tasks 的语义；团队增强只补充协作上下文，不把产物改成会议纪要或项目管理文档。
- **重要**：\`context\` 和 \`rules\` 是给你的约束，不是产物内容。
  - 不要把 \`<context>\`、\`<rules>\`、\`<project_context>\` 块复制进输出文件。
  - 它们指导你写什么，但不应该出现在最终文件中。

**护栏**

- 创建 schema 的 \`apply.requires\` 定义的所有实现前产物。
- 始终先读依赖产物，再写新产物。
- 对关键业务、契约、迁移、跨团队 owner 不明确的地方要询问，不要臆测。
- 团队或 API/YAPI 信息不完整时，必须在产物中保留 unknown/TBD 和确认对象，不能把缺口藏在对话里。
- 涉及 API 的 change 必须在 tasks.md 中包含 YAPI create/update、Mock/advmock 和 audit/一致性核对任务。
- 如果同名变更已存在，询问用户是继续该变更还是创建新变更。
- 写完每个产物后确认文件存在，再继续下一个。`;

export function getOvsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'ovsespec-propose',
    description: '创建新的 OvseSpec 变更，并一次生成实现前所需产物；团队场景会补充影响范围、owner、评审、迁移和交接信息。',
    instructions: PROPOSE_INSTRUCTIONS,
    license: 'MIT',
    compatibility: 'Requires ovsespec CLI.',
    metadata: { author: 'ovsespec', version: '1.0' },
  };
}

export function getOvsxProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'OVSX: Propose',
    description: '创建新变更并一次生成 proposal、design、tasks；团队场景补充协作上下文',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'team'],
    content: PROPOSE_INSTRUCTIONS,
  };
}
